swagger: "2.0"
info:
  description: "Backend API for an ecommerce project"
  version: "1.0.0"
  title: "E-Commerce"
tags:
- name: "customers"
  description: "Everything about your Pets"
schemes:
- "https"
- "http"
paths:
  /customers:
    post:
      tags:
      - "customers"
      summary: "Add new customers"
      description: ""
      operationId: "addCustomer"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        400:
          description: "Invalid input"
      
